name: Publish release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get current tag
        id: tag
        run: |
          git fetch --tags --force
          tag=$(git tag -l --points-at HEAD)
          vtag=$(echo $tag | grep "^v[0-9]\+\.[0-9]\+\.[0-9]\+" || echo "")
          echo "##[set-output name=currenttag;]$vtag"

      - name: Publish
        if: ${{ startsWith( steps.tag.outputs.currenttag , 'v' ) }}
        - uses: actions/setup-node@v1
          with:
            node-version: '12'
            registry-url: 'https://registry.npmjs.org'
        run: |
          npm install
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
